"""`gsuite completion` — shell tab-completion scripts, generated at runtime
from the CLI's own argparse tree (no hardcoded command lists: like the
reference docs, completions can never drift from the code)."""
from __future__ import annotations

import argparse

from gsuite.cmdreg import Cmd, register_service


def _sub_action(parser) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _words(parser) -> list[str]:
    """Completion words offered at one parser's level: subcommand names
    first (registration order), then option strings."""
    words: list[str] = []
    sub = _sub_action(parser)
    if sub is not None:
        words += list(sub.choices)
    for action in parser._actions:
        words += action.option_strings
    return words


def _walk(parser, path: str, table: list[tuple[str, list[str]]]) -> None:
    """Depth-first, registration-order walk: path -> completion words."""
    table.append((path, _words(parser)))
    sub = _sub_action(parser)
    if sub is not None:
        for name, child in sub.choices.items():
            _walk(child, f"{path} {name}", table)


def _bash_script() -> str:
    # Imported here, not at module top: cli imports this module at
    # parser-build time, so a top-level import would be a cycle.
    from gsuite.cli import build_parser

    table: list[tuple[str, list[str]]] = []
    _walk(build_parser(), "gsuite", table)
    lines = [
        "# bash completion for gsuite — generated by `gsuite completion bash`",
        "_gsuite() {",
        '    local cur="${COMP_WORDS[COMP_CWORD]}"',
        '    local path="" w words=""',
        '    for w in "${COMP_WORDS[@]:0:COMP_CWORD}"; do',
        '        case "$w" in -*) continue ;; esac',
        '        if [ -z "$path" ]; then path="$w"; else path="$path $w"; fi',
        "    done",
        '    case "$path" in',
    ]
    for path, words in table:
        lines.append(f'        "{path}") words="{" ".join(words)}" ;;')
    lines += [
        "    esac",
        '    COMPREPLY=( $(compgen -W "$words" -- "$cur") )',
        "}",
        "complete -F _gsuite gsuite",
    ]
    return "\n".join(lines) + "\n"


def cmd_bash(args) -> int:
    print(_bash_script(), end="")
    return 0


def cmd_zsh(args) -> int:
    # Standard shim: zsh's bashcompinit runs bash-style completion
    # functions natively, so the payload is byte-identical to bash.
    print("autoload -U +X bashcompinit && bashcompinit")
    print(_bash_script(), end="")
    return 0


def register(subparsers) -> None:
    register_service(subparsers, "completion",
                     "shell tab-completion (generated from the parser tree)", [
        Cmd("bash", cmd_bash, "print a bash completion script"),
        Cmd("zsh", cmd_zsh, "print a zsh completion script (bashcompinit shim)"),
    ])
